# Generated by Django 5.2.8 on 2025-11-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking')], max_length=20)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestAccrual',
            fields=[
                ('accrual_id', models.AutoField(primary_key=True, serialize=False)),
                ('accrual_date', models.DateField()),
                ('interest_earned', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_snapshot', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_compounded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-accrual_date'],
            },
        ),
    ]
