# Generated by Django 5.2.8 on 2025-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanapplication_loan_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='term_months',
            field=models.IntegerField(default=12),
        ),
    ]
