# Generated by Django 5.2.8 on 2025-11-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanapplication_term_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='agreement_document',
            field=models.FileField(blank=True, null=True, upload_to='loan_agreements/'),
        ),
    ]
