# Generated by Django 5.2.8 on 2025-11-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_agreement_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizationschedule',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
