# Generated by Django 5.2.8 on 2025-11-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_amortizationschedule_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
