# Generated by Django 5.2.8 on 2025-11-23 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('notification_type', models.CharField(choices=[('payment_reminder', 'Payment Reminder'), ('loan_approved', 'Loan Approved'), ('due_date', 'Due Date'), ('system_alert', 'System Alert')], max_length=50)),
                ('related_entity_type', models.CharField(choices=[('loan', 'loan'), ('account', 'account'), ('system', 'system')], max_length=20)),
                ('related_entity_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
